/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;


import administration.SuratJalan;
import administration.invoice;
import administration.laporan;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.*;
import java.sql.DriverManager;;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import karyawan.dataKaryawan;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import proyek.DataProyek;
import vehicles.dataKendaraan;



/**
 *
 * @author Anna Karenina
 */
public class Dashboard extends javax.swing.JFrame {
    
    Connection c = getConnection();
    
    Color panelclicked;
    Color paneldefault;
    public Dashboard() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        panelclicked = new Color(102,102,225);
        paneldefault = new Color(0,0,102);
        jPanel3.setBackground(panelclicked);
        jPanel5.setBackground(paneldefault);
        jPanel6.setBackground(paneldefault);
        jPanel7.setBackground(paneldefault);
        jPanel8.setBackground(paneldefault);
        jPanel9.setBackground(paneldefault);
        ctpnl.setLayout(new java.awt.BorderLayout());
        autochar();
    }
    public Connection getConnection(){
        Connection con;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tnj", "root", "");
            return con;
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ctpnl = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        armada = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        supplies = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        karyawan = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        administ = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Anna Karenina Jusuf");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UI/UX Designer");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\dashboard.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 60));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\karyawan.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 60));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\kendaraan.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 60));

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\proyek.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, 60));

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));

        jLabel15.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\administrasi.png")); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, 60));

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\logout.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 881));

        center.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel28.setText("Surat Jalan");
        dashboard.add(jLabel28);
        jLabel28.setBounds(40, 70, 90, 20);

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel31.setText("100");
        dashboard.add(jLabel31);
        jLabel31.setBounds(40, 180, 90, 17);

        jLabel16.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\surat jalan.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        dashboard.add(jLabel16);
        jLabel16.setBounds(20, 60, 260, 160);

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel27.setText("Invoice");
        dashboard.add(jLabel27);
        jLabel27.setBounds(880, 70, 90, 20);

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel30.setText("100");
        dashboard.add(jLabel30);
        jLabel30.setBounds(880, 180, 90, 17);

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel26.setText("Laporan");
        dashboard.add(jLabel26);
        jLabel26.setBounds(600, 70, 160, 20);

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel29.setText("100");
        dashboard.add(jLabel29);
        jLabel29.setBounds(600, 180, 90, 17);

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel23.setText("Data Proyek");
        dashboard.add(jLabel23);
        jLabel23.setBounds(320, 70, 130, 20);

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel22.setText("100");
        dashboard.add(jLabel22);
        jLabel22.setBounds(320, 180, 90, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\data proyek.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        dashboard.add(jLabel17);
        jLabel17.setBounds(300, 60, 260, 160);

        jLabel18.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\laporan.png")); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        dashboard.add(jLabel18);
        jLabel18.setBounds(580, 60, 260, 160);

        jLabel19.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\invoice.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        dashboard.add(jLabel19);
        jLabel19.setBounds(860, 60, 260, 160);

        jLabel20.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        dashboard.add(jLabel20);
        jLabel20.setBounds(1100, 10, 10, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        dashboard.add(jLabel21);
        jLabel21.setBounds(1120, 10, 10, 10);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel24.setText("Statistik");
        dashboard.add(jLabel24);
        jLabel24.setBounds(20, 240, 140, 20);

        javax.swing.GroupLayout ctpnlLayout = new javax.swing.GroupLayout(ctpnl);
        ctpnl.setLayout(ctpnlLayout);
        ctpnlLayout.setHorizontalGroup(
            ctpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        ctpnlLayout.setVerticalGroup(
            ctpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        dashboard.add(ctpnl);
        ctpnl.setBounds(20, 280, 820, 430);

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel25.setText("Highlight bulan ini");
        dashboard.add(jLabel25);
        jLabel25.setBounds(20, 20, 160, 20);

        center.add(dashboard, "card3");

        armada.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel41.setText("Data Kendaraan");
        jPanel10.add(jLabel41);
        jLabel41.setBounds(40, 70, 120, 20);

        jLabel42.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\data kendaraan.png")); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel42);
        jLabel42.setBounds(20, 60, 260, 160);

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel45.setText("Kendaraan");
        jPanel10.add(jLabel45);
        jLabel45.setBounds(20, 20, 120, 20);

        jLabel50.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel50);
        jLabel50.setBounds(1100, 10, 10, 10);

        jLabel51.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel51);
        jLabel51.setBounds(1120, 10, 10, 10);

        javax.swing.GroupLayout armadaLayout = new javax.swing.GroupLayout(armada);
        armada.setLayout(armadaLayout);
        armadaLayout.setHorizontalGroup(
            armadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        armadaLayout.setVerticalGroup(
            armadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );

        center.add(armada, "card4");

        supplies.setBackground(new java.awt.Color(255, 255, 255));
        supplies.setForeground(new java.awt.Color(0, 0, 102));
        supplies.setLayout(null);

        jLabel74.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel74.setText("Data Proyek");
        supplies.add(jLabel74);
        jLabel74.setBounds(38, 32, 100, 20);

        jLabel78.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel78.setText("Projek Berjalan");
        supplies.add(jLabel78);
        jLabel78.setBounds(60, 90, 120, 20);

        jLabel75.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel75MouseClicked(evt);
            }
        });
        supplies.add(jLabel75);
        jLabel75.setBounds(1100, 10, 10, 10);

        jLabel76.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel76MouseClicked(evt);
            }
        });
        supplies.add(jLabel76);
        jLabel76.setBounds(1120, 10, 10, 10);

        jLabel77.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\proyek berjalan.png")); // NOI18N
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });
        supplies.add(jLabel77);
        jLabel77.setBounds(40, 80, 260, 160);

        center.add(supplies, "card5");

        karyawan.setBackground(new java.awt.Color(255, 255, 255));
        karyawan.setLayout(null);

        jLabel40.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel40.setText("Karyawan");
        karyawan.add(jLabel40);
        jLabel40.setBounds(20, 20, 120, 20);

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel35.setText("Data Karyawan");
        karyawan.add(jLabel35);
        jLabel35.setBounds(40, 70, 120, 20);
        karyawan.add(jLabel10);
        jLabel10.setBounds(460, 364, 0, 0);

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        karyawan.add(jLabel12);
        jLabel12.setBounds(1120, 10, 10, 10);

        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        karyawan.add(jLabel13);
        jLabel13.setBounds(1100, 10, 10, 10);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\data karyawan.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        karyawan.add(jLabel8);
        jLabel8.setBounds(20, 60, 260, 160);

        center.add(karyawan, "card2");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel54.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel54.setText("Administrasi");
        jPanel4.add(jLabel54);
        jLabel54.setBounds(20, 20, 120, 20);

        jLabel56.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel56.setText("Surat Jalan");
        jPanel4.add(jLabel56);
        jLabel56.setBounds(40, 70, 120, 20);

        jLabel57.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel57.setText("Surat Isi Muatan");
        jPanel4.add(jLabel57);
        jLabel57.setBounds(320, 70, 120, 20);

        jLabel58.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel58.setText("Laporan");
        jPanel4.add(jLabel58);
        jLabel58.setBounds(600, 70, 160, 20);

        jLabel59.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel59.setText("Invoice");
        jPanel4.add(jLabel59);
        jLabel59.setBounds(880, 70, 120, 20);
        jPanel4.add(jLabel61);
        jLabel61.setBounds(460, 364, 0, 0);

        jLabel62.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel62);
        jLabel62.setBounds(1120, 10, 10, 10);

        jLabel63.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel63);
        jLabel63.setBounds(1100, 10, 10, 10);

        jLabel64.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\surat jalan.png")); // NOI18N
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel64);
        jLabel64.setBounds(20, 60, 260, 160);

        jLabel65.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\surat isi muatan.png")); // NOI18N
        jPanel4.add(jLabel65);
        jLabel65.setBounds(300, 60, 260, 160);

        jLabel66.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\laporan.png")); // NOI18N
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel66);
        jLabel66.setBounds(580, 60, 260, 160);

        jLabel67.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\ilustration\\invoice.png")); // NOI18N
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel67MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel67);
        jLabel67.setBounds(860, 60, 260, 160);

        javax.swing.GroupLayout administLayout = new javax.swing.GroupLayout(administ);
        administ.setLayout(administLayout);
        administLayout.setHorizontalGroup(
            administLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        administLayout.setVerticalGroup(
            administLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );

        center.add(administ, "card6");

        jPanel1.add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1, 1260, 880));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked
        if (evt.getSource()==jLabel1){
            dashboard.setVisible(true);
            karyawan.setVisible(false);
            armada.setVisible(false);
            supplies.setVisible(false);
            administ.setVisible(false);
           
            jPanel3.setBackground(panelclicked);
            jPanel5.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
        }
            else if (evt.getSource()==jLabel2){
            dashboard.setVisible(false);
            karyawan.setVisible(true);
            armada.setVisible(false);
            supplies.setVisible(false);
            administ.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(panelclicked);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
        }
        else if (evt.getSource()==jLabel3){
            dashboard.setVisible(false);
            karyawan.setVisible(false);
            armada.setVisible(true);
            supplies.setVisible(false);
            administ.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(panelclicked);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
        }
            else if (evt.getSource()==jLabel4){
            dashboard.setVisible(false);
            karyawan.setVisible(false);
            armada.setVisible(false);
            supplies.setVisible(true);
            administ.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(panelclicked);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
         } else if (evt.getSource()==jLabel15){
            dashboard.setVisible(false);
            karyawan.setVisible(false);
            armada.setVisible(false);
            supplies.setVisible(false);
            administ.setVisible(true);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(panelclicked);
            jPanel9.setBackground(paneldefault);
         }
        else if (evt.getSource()==jLabel5){
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(panelclicked);
            try {
            int yn = JOptionPane.showConfirmDialog(null, "Keluar aplikasi ?", "Keluar", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                Login l = new Login();
                l.setVisible(true);
                this.dispose();
            } else {
                
            }
            
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
           
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(panelclicked);
            jPanel9.setBackground(paneldefault);
         }
        
    }//GEN-LAST:event_MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        setExtendedState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dataKaryawan dk = new dataKaryawan();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
           dataKendaraan dk = new dataKendaraan();
           dk.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
      this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        SuratJalan sj = new SuratJalan();
        sj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        SuratJalan sj = new SuratJalan();
        sj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel75MouseClicked

    private void jLabel76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel76MouseClicked

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        DataProyek d = new DataProyek();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        laporan l = new laporan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseClicked
        invoice in = new invoice();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel67MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
    DataProyek p = new proyek.DataProyek();
    p.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
       laporan l = new laporan();
               l.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
       invoice in = new invoice();
       in.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked
private DefaultCategoryDataset createDataset() {
        // same dataset for line chart and bar chart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "products", "1970");
        dataset.addValue(30, "products", "1980");
        dataset.addValue(60, "products", "1990");
        dataset.addValue(120, "products", "2000");
        dataset.addValue(240, "products", "2010");
        dataset.addValue(300, "products", "2014");

        return dataset;
    }   
   private void autochar(){
       DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("TV", new Double(20));
        dataset.setValue("DVD", new Double(20));
        dataset.setValue("Mobile phone", new Double(40));
        dataset.setValue("Accessories", new Double(10));
        // create pir chart
        JFreeChart chart = ChartFactory.createPieChart3D(
                "Product Sales", // chart title                   
                dataset, // data 
                true, // include legend                   
                true,
                false);
        // set chart properties
        final PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(270);
        plot.setForegroundAlpha(0.60f);
        plot.setInteriorGap(0.02);
        // create chart panel the add it to swing panel in  jframe
        ChartPanel chartPanel = new ChartPanel(chart);
        ctpnl.removeAll();        // clear panel before add new chart
        ctpnl.add(chartPanel, BorderLayout.CENTER);
        ctpnl.validate();      
   }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel administ;
    private javax.swing.JPanel armada;
    private javax.swing.JPanel center;
    private javax.swing.JPanel ctpnl;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel karyawan;
    private javax.swing.JPanel supplies;
    // End of variables declaration//GEN-END:variables
}
