/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administration;

import static administration.SuratJalan.tabelsj;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.Dashboard;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Anna Karenina
 */
public class invoice extends javax.swing.JFrame {
    Connection c = getConnection();
    SimpleDateFormat date = new SimpleDateFormat("dd-MMM-yyyy");
    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        dataInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelinvoice = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\back.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\bar invoice.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\add.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\edit.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\delete.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\refresh.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\cetak.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 200, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setText("Cari disini..");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));

        tabelinvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16"
            }
        ));
        tabelinvoice.setGridColor(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(tabelinvoice);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1310, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Connection getConnection(){
        Connection con;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tnj", "root", "");
            return con;
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }
    public static void AddRowToJTable(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)tabelinvoice.getModel();
        model.addRow(dataRow);
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        addInvoice k = new addInvoice();
        k.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try{ int i = tabelinvoice.getSelectedRow();
            TableModel mode = tabelinvoice.getModel();

            editInvoice edit = new editInvoice();
            edit.setVisible(true);

            edit.jTextField1.setText(mode.getValueAt(i, 0).toString());
            edit.jTextField2.setText(mode.getValueAt(i, 1).toString());
            edit.jTextField4.setText(mode.getValueAt(i,2).toString());
            edit.jTextField8.setText(mode.getValueAt(i, 3).toString());
            edit.jTextArea1.setText(mode.getValueAt(i, 4).toString());
            java.util.Date dt = date.parse((String)mode.getValueAt(i, 5));
            java.util.Date dt2 = date.parse((String)mode.getValueAt(i, 6));
            edit.jDateChooser1.setDate(dt);
            edit.jDateChooser2.setDate(dt2);
            edit.jTextField7.setText(mode.getValueAt(i, 7).toString());
            edit.jTextField6.setText(mode.getValueAt(i, 8).toString());
            edit.jTextField5.setText(mode.getValueAt(i, 9).toString());
            

        } catch(Exception e){

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        int i = tabelinvoice.getSelectedRow();
        TableModel mode = tabelinvoice.getModel();

        try {
            int yn = JOptionPane.showConfirmDialog(null, "Yakin menghapus data ?", "Hapus data", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                PreparedStatement ps = c.prepareStatement("delete from invoice where no_inv='"+mode.getValueAt(i, 0).toString()+"'");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data terhapus");
                dataInvoice();
            } else {

            }

        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dataInvoice();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        Object [] header = {"Nomor invoice","Id Proyek","Nama Proyek","Invoice untuk","Alamat penagihan","Dikeluarkan pada","Jatuh tempo","Sub total","Pajak","Total"
        };
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelinvoice.setModel(model);
        try{

            PreparedStatement ps = c.prepareStatement("SELECT invoice.no_inv, data_proyek.id, data_proyek.nama, data_proyek.pj, data_proyek.lokasi, invoice.date, invoice.due_date, invoice.sub_total, invoice.tax, invoice.total "
                    + "FROM invoice INNER JOIN data_proyek ON invoice.id=data_proyek.id where concat(invoice.no_inv, data_proyek.id, data_proyek.nama, data_proyek.pj, data_proyek.lokasi, invoice.date, invoice.due_date, invoice.sub_total, invoice.tax, invoice.total) like '%"+jTextField1.getText()+"%'  ORDER BY data_proyek.nama ASC");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("invoice.no_inv");
                String c2 = rs.getString("data_proyek.id");
                String c3 = rs.getString("data_proyek.nama");
                String c4 = rs.getString("data_proyek.pj");
                String c5 = rs.getString("data_proyek.lokasi");
                String c6 = rs.getString("invoice.date");
                String c7 = rs.getString("invoice.due_date");
                String c8 = rs.getString("invoice.sub_total");
                String c9 = rs.getString("invoice.tax");
                String c10 = rs.getString("invoice.total");
                String[] data = {c1,c2,c3,c4,c5,c6,c7,c8,c9,c10};
                model.addRow(data);
            }
        } catch( Exception e){

        }
    }//GEN-LAST:event_jTextField1KeyReleased
 private void dataInvoice(){
        Object [] header = {"Nomor invoice","Id Proyek","Nama Proyek","Invoice untuk","Alamat penagihan","Dikeluarkan pada","Jatuh tempo","Sub total","Pajak","Total"
        };
        DefaultTableModel model = new DefaultTableModel(null,header);
       tabelinvoice.setModel(model);
        try{
            
            PreparedStatement ps = c.prepareStatement("SELECT invoice.no_inv, data_proyek.id, data_proyek.nama, data_proyek.pj, data_proyek.lokasi, invoice.date, invoice.due_date, invoice.sub_total, invoice.tax, invoice.total "
                    + "FROM invoice INNER JOIN data_proyek ON invoice.id=data_proyek.id ORDER BY data_proyek.nama ASC ");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("invoice.no_inv");
                String c2 = rs.getString("data_proyek.id");
                String c3 = rs.getString("data_proyek.nama");
                String c4 = rs.getString("data_proyek.pj");
                String c5 = rs.getString("data_proyek.lokasi");
                String c6 = rs.getString("invoice.date");
                String c7 = rs.getString("invoice.due_date");
                String c8 = rs.getString("invoice.sub_total");
                String c9 = rs.getString("invoice.tax");
                String c10 = rs.getString("invoice.total");
                String[] data = {c1,c2,c3,c4,c5,c6,c7,c8,c9,c10};
                model.addRow(data);
            }
        } catch( Exception e){

        }
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Dashboard d = new Dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        int i = tabelinvoice.getSelectedRow();
        TableModel mode = tabelinvoice.getModel();
        String idp = mode.getValueAt(i, 1).toString();
        try {
            HashMap param = new HashMap();
            param.put("idproyek",idp);
            String rpt = "src/report/invoice.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rpt);
            JasperPrint jpp = JasperFillManager.fillReport(jr, param,c);
            JasperViewer.viewReport(jpp,false);
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTable tabelinvoice;
    // End of variables declaration//GEN-END:variables
}
