/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administration;

import static administration.invoice.tabelinvoice;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.Dashboard;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Anna Karenina
 */
public class SuratJalan extends javax.swing.JFrame {

    SimpleDateFormat date = new SimpleDateFormat("dd-MMM-yyyy hh:mm:ss a");
        Connection c = getConnection();
        DefaultTableModel mode = new DefaultTableModel();
    public SuratJalan() {
        initComponents();
         dataSuratjalan();
        setExtendedState(MAXIMIZED_BOTH);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelsj = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\back.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\minim.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\close.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\nav bar surat jalan.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\add.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\edit.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\delete.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        tabelsj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane2.setViewportView(tabelsj);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1300, 610));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\refresh.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setText("Cari disini..");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 200, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\Selena Gomes\\A\\TNJ\\Company App\\Bahan\\cetak.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Connection getConnection(){
        Connection con;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tnj", "root", "");
            return con;
        } catch (SQLException ex) {
        }
        return null;
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Dashboard d = new Dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        AddSJ add = new AddSJ();
        add.setVisible(true);
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try
        { int i = tabelsj.getSelectedRow();
            TableModel mode = tabelsj.getModel();

            editSJ edit = new editSJ();
            edit.setVisible(true);
            java.util.Date dt = date.parse((String)mode.getValueAt(i, 0));
            edit.jDateChooser1.setDate(dt);
            edit.jTextField11.setText(mode.getValueAt(i, 1).toString());
            edit.jTextField2.setText(mode.getValueAt(i,2).toString());
            edit.jTextField3.setText(mode.getValueAt(i,3).toString());
            edit.jTextField4.setText(mode.getValueAt(i, 4).toString());
            edit.jTextField5.setText(mode.getValueAt(i,5).toString());
            edit.jTextField6.setText(mode.getValueAt(i, 6).toString());
            edit.jTextField7.setText(mode.getValueAt(i,7).toString());
            edit.jTextField12.setText(mode.getValueAt(i, 8).toString());
            edit.jTextField8.setText(mode.getValueAt(i, 9).toString());
            edit.jTextField9.setText(mode.getValueAt(i, 10).toString());
            edit.jTextField10.setText(mode.getValueAt(i, 11).toString());
            edit.jTextField13.setText(mode.getValueAt(i, 12).toString());
            edit.jTextField15.setText(mode.getValueAt(i, 13).toString());
            
        } catch(Exception e){

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        int i = tabelsj.getSelectedRow();
        TableModel mode = tabelsj.getModel();
            
        try {
            int yn = JOptionPane.showConfirmDialog(null, "Yakin menghapus data ?", "Hapus data", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                PreparedStatement ps = c.prepareStatement("delete from surat_jalan where no_surat='"+mode.getValueAt(i, 2).toString()+"'");
                ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data terhapus");
               dataSuratjalan();
            } else {
                
            }
            
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
    }//GEN-LAST:event_jLabel11MouseClicked
     public static void AddRowToJTable(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)tabelsj.getModel();
        model.addRow(dataRow);
    }
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       dataSuratjalan();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
         Object [] header = {"Tanggal","Kode Proyek","No.surat","NIP","Nama","No.Kendaraan","No.Polisi","Pickup Point","Drop Point","Material","Jarak Tempuh","Uang Jalan","Berat","Harga"
        };
        DefaultTableModel model = new DefaultTableModel(null,header);
       tabelsj.setModel(model);
        try{
            
            PreparedStatement ps = c.prepareStatement("SELECT surat_jalan.tanggal, surat_jalan.id, surat_jalan.no_surat, surat_jalan.nip,surat_jalan.berat,surat_jalan.harga,"
                    + " karyawan.nama, surat_jalan.no_ken, kendaraan.no_pol, data_proyek.pickup, data_proyek.dropp, surat_jalan.material, "
                    + "surat_jalan.jartem, surat_jalan.uang_jalan FROM surat_jalan INNER JOIN karyawan ON surat_jalan.nip = karyawan.nip "
                    + "INNER JOIN kendaraan ON surat_jalan.no_ken = kendaraan.no_ken INNER JOIN data_proyek ON surat_jalan.id = data_proyek.id "
                    + "WHERE CONCAT( surat_jalan.tanggal, surat_jalan.jartem, surat_jalan.id, surat_jalan.no_surat, surat_jalan.nip, surat_jalan.no_ken, "
                    + "kendaraan.no_pol, data_proyek.pickup, data_proyek.dropp, surat_jalan.material, karyawan.nama, surat_jalan.uang_jalan ) "
                    + "like '%"+jTextField2.getText()+"%' ORDER BY surat_jalan.tanggal DESC");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("surat_jalan.tanggal");
                String c2 = rs.getString("surat_jalan.id");
                String c3 = rs.getString("surat_jalan.no_surat");
                String c4 = rs.getString("surat_jalan.nip");
                String c5 = rs.getString("karyawan.nama");
                String c6 = rs.getString("surat_jalan.no_ken");
                String c7 = rs.getString("kendaraan.no_pol");
                String c8 = rs.getString("data_proyek.pickup");
                String c9 = rs.getString("data_proyek.dropp");
                String c10 = rs.getString("surat_jalan.material");
                String c11 = rs.getString("surat_jalan.jartem");
                String c12 = rs.getString("surat_jalan.uang_jalan");
                String c13 = rs.getString("surat_jalan.berat");
                String c14 = rs.getString("surat_jalan.harga");
                String[] data = {c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14};
                model.addRow(data);
            }
        } catch( SQLException e){

        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       int i = tabelsj.getSelectedRow();
        TableModel mode = tabelsj.getModel();
        String idp = mode.getValueAt(i, 2).toString();
        System.out.println(idp);
        try {
            HashMap param = new HashMap();
            param.put("ns",idp);
            String rpt = "src/report/ssj.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rpt);
            JasperPrint jpp = JasperFillManager.fillReport(jr, param,c);
            JasperViewer.viewReport(jpp,false);
            
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel10MouseClicked
    private void dataSuratjalan(){
        Object [] header = {"Tanggal","Kode Proyek","No.surat","NIP","Nama","No.Kendaraan","No.Polisi","Pickup Point","Drop Point","Material","Jarak Tempuh","Uang Jalan","Berat","Harga"
        };
        DefaultTableModel model = new DefaultTableModel(null,header);
       tabelsj.setModel(model);
        try{
            
            PreparedStatement ps = c.prepareStatement("SELECT surat_jalan.tanggal, surat_jalan.id, surat_jalan.no_surat, surat_jalan.nip,surat_jalan.no_ken,surat_jalan.berat, karyawan.nama,kendaraan.no_pol, data_proyek.pickup, data_proyek.dropp, surat_jalan.material, surat_jalan.jartem, surat_jalan.uang_jalan, surat_jalan.harga from surat_jalan "
                    + "INNER JOIN karyawan ON surat_jalan.nip=karyawan.nip INNER JOIN kendaraan on surat_jalan.no_ken=kendaraan.no_ken INNER JOIN data_proyek on surat_jalan.id=data_proyek.id ORDER BY surat_jalan.tanggal DESC");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("surat_jalan.tanggal");
                String c2 = rs.getString("surat_jalan.id");
                String c3 = rs.getString("surat_jalan.no_surat");
                String c4 = rs.getString("surat_jalan.nip");
                String c5 = rs.getString("karyawan.nama");
                String c6 = rs.getString("surat_jalan.no_ken");
                String c7 = rs.getString("kendaraan.no_pol");
                String c8 = rs.getString("data_proyek.pickup");
                String c9 = rs.getString("data_proyek.dropp");
                String c10 = rs.getString("surat_jalan.material");
                String c11 = rs.getString("surat_jalan.jartem");
                String c12 = rs.getString("surat_jalan.uang_jalan");
                String c13 = rs.getString("surat_jalan.berat");
                String c14 = rs.getString("surat_jalan.harga");
                String[] data = {c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14};
                model.addRow(data);
            }
        } catch( Exception e){

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuratJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuratJalan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTable tabelsj;
    // End of variables declaration//GEN-END:variables
}
